### ISSUE TITLE
Issue Running Provided Code Example

### ISSUE THREAD

**Issue by yuhsuan2014** [Aidenzich/helloBERTopic#1]
Hi, 
Thank you for sharing your code. However, I'm unable to run the example provided. Initially, I attempted to run it using PyCharm and Anaconda, then on Colab, and also tried different computers. I suspect the issue may be related to the 'lib' component. Could you please review it and possibly update the version? Thank you very much for your assistance.

**Comment by Aidenzich** [comment]
Hey @yuhsuan2014 , thank you for bringing this issue to my attention. I have updated the dependencies and specified the Python version to Python 3.9. Now, it should work as expected.

**Comment by yuhsuan2014** [comment]
I deeply appreciate your updating the code. It works very well now.
